version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 606886439950.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t assign03 .
      - docker tag assign03:latest 606886439950.dkr.ecr.us-east-1.amazonaws.com/assign03:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 606886439950.dkr.ecr.us-east-1.amazonaws.com/assign03:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"assign03-contianer","imageUri":"606886439950.dkr.ecr.us-east-1.amazonaws.com/assign03:latest"}]' > imagedefinitions.json
      - echo "Updating ECS service to use the latest image..."
      - aws ecs update-service --cluster assign03-cluster --service assign03service --force-new-deployment
      - echo "imagedefinitions.json created successfully."
      - echo "Build completed on $(date)"
      
artifacts:
  files:
    - imagedefinitions.json
